# -*- coding: utf-8 -*-
"""color detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s5EjqKtR44rhFQRvO4LUcTsKq96-AA3a
"""

import cv2 as cv
import matplotlib.pyplot as plt
from PIL import Image
img = cv.imread("/content/drive/MyDrive/1102813.jpg")

blur = cv.blur(img,(5,5))
blur0=cv.medianBlur(blur,5)
blur1= cv.GaussianBlur(blur0,(5,5),0)
blur2= cv.bilateralFilter(blur1,9,75,75)

hsv = cv.cvtColor(blur2, cv.COLOR_BGR2HSV)

#for blue color
import numpy as np
low_blue = np.array([70, 50, 50])
high_blue = np.array([110, 255, 255])
mask = cv.inRange(hsv, low_blue, high_blue)

res = cv.bitwise_and(img,img, mask= mask)

from google.colab.patches import cv2_imshow
cv2_imshow(res)

#for red color
import numpy as np
low_red = np.array([130, 90, 145])
high_red = np.array([198, 255, 255])
mask = cv.inRange(hsv, low_red, high_red)

res = cv.bitwise_and(img,img, mask= mask)

from google.colab.patches import cv2_imshow
cv2_imshow(res)

#for green color
import numpy as np
low_green = np.array([40, 62, 160])
high_green = np.array([78, 255, 255])
mask = cv.inRange(hsv, low_green, high_green)

res = cv.bitwise_and(img,img, mask= mask)

from google.colab.patches import cv2_imshow
cv2_imshow(res)

#for green color
import numpy as np
low_yellow = np.array([20, 20, 40])
high_yellow = np.array([30, 255, 255])
mask = cv.inRange(hsv, low_yellow, high_yellow)

res = cv.bitwise_and(img,img, mask= mask)

from google.colab.patches import cv2_imshow
cv2_imshow(res)











